# Generated by Django 4.1.1 on 2022-09-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='accounting.category')),
            ],
        ),
    ]
