# Generated by Django 4.1.1 on 2022-10-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_category_options_category_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingunit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accountingunit',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
