# Generated by Django 4.1.1 on 2022-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expensesunit_incomeunit_delete_accountingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesunit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expensesunit',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='incomeunit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='incomeunit',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
